export type NavItem = {
	label: string;
	slug: string;
};

export const navItems: NavItem[] = [
	{ label: 'Avatar', slug: 'avatar' },
	{ label: 'Button', slug: 'button' },
	{ label: 'Card', slug: 'card' },
	{ label: 'Carousel', slug: 'carousel' },
	{ label: 'Checkbox', slug: 'checkbox' },
	{ label: 'Collapsible', slug: 'collapsible' },
	{ label: 'Combobox', slug: 'combobox' },
	{ label: 'Date Field', slug: 'date-field' },
	{ label: 'Date Input', slug: 'date-input' },
	{ label: 'Date Picker', slug: 'date-picker' },
	{ label: 'Date Range Field', slug: 'date-range-field' },
	{ label: 'Data Table v9', slug: 'data-table-v9' },
	{ label: 'Dialog', slug: 'dialog' },
	{ label: 'Drawer', slug: 'drawer' },
	{ label: 'Field', slug: 'field' },
	{ label: 'Fieldset', slug: 'fieldset' },
	{ label: 'File Upload', slug: 'file-upload' },
	{ label: 'Hover Card', slug: 'hover-card' },
	{ label: 'Image Cropper', slug: 'image-cropper' },
	{ label: 'Image Upload', slug: 'image-upload' },
	{ label: 'Json Tree View', slug: 'json-tree-view' },
	{ label: 'Listbox', slug: 'listbox' },
	{ label: 'Menu', slug: 'menu' },
	{ label: 'Number Input', slug: 'number-input' },
	{ label: 'Palette', slug: 'palette' },
	{ label: 'Password Input', slug: 'password-input' },
	{ label: 'Phone Input', slug: 'phone-input' },
	{ label: 'Popover', slug: 'popover' },
	{ label: 'QR Code', slug: 'qr-code' },
	{ label: 'Scroll Area', slug: 'scroll-area' },
	{ label: 'Select', slug: 'select' },
	{ label: 'Splitter', slug: 'splitter' },
	{ label: 'Switch', slug: 'switch' },
	{ label: 'Tags Input', slug: 'tags-input' },
	{ label: 'Toast', slug: 'toast' },
	{ label: 'Toggle', slug: 'toggle' },
	{ label: 'Tooltip', slug: 'tooltip' },
	{ label: 'Tree View', slug: 'tree-view' }
];
